/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HZ20S.c                                               *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x6D4B (27979)                                *
* Character enabled:   0x91CF (37327)                                *
* Character enabled:   0x663E (26174)                                *
* Character enabled:   0x793A (31034)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHZ20S;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontHZ20S_663E[ 45] = { /* code 663E */
  __XXXXXX,XXXXXXXX,________,
  __X_____,_______X,________,
  __X_____,_______X,________,
  __XXXXXX,XXXXXXXX,________,
  __X_____,_______X,________,
  __X_____,_______X,________,
  __XXXXXX,XXXXXXXX,________,
  __X_____,_______X,________,
  _X____X_,___X____,X_______,
  __X___X_,___X___X,________,
  __XX__X_,___X__XX,________,
  ___XX_X_,___X__X_,________,
  ____X_X_,___X_X__,________,
  ______X_,___X____,________,
  XXXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ20S_6D4B[ 51] = { /* code 6D4B */
  _X______,________,X_______,
  _XX__XXX,XXX__X__,X_______,
  __XX_X__,__X__X__,X_______,
  _____X__,__X__X__,X_______,
  _____X__,X_X__X__,X_______,
  XX___X__,X_X__X__,X_______,
  _XX__X__,X_X__X__,X_______,
  __XX_X__,X_X__X__,X_______,
  _____X__,X_X__X__,X_______,
  _____X__,X_X__X__,X_______,
  ___X_X__,X_X__X__,X_______,
  ___X_X__,X_X__X__,X_______,
  __X____X,X____X__,X_______,
  __X____X,XX______,X_______,
  __X___X_,_X______,X_______,
  _X__XX__,__X_____,X_______,
  _X_XX___,___X_XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ20S_793A[ 48] = { /* code 793A */
  __XXXXXX,XXXXXXXX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  XXXXXXXX,XXXXXXXX,XX______,
  ________,_X______,________,
  ____X___,_X___X__,________,
  ___XX___,_X____X_,________,
  ___X____,_X____XX,________,
  __X_____,_X_____X,________,
  _XX_____,_X______,X_______,
  _X______,_X______,XX______,
  X_______,_X______,_X______,
  ________,_X______,________,
  _____XXX,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ20S_91CF[ 45] = { /* code 91CF */
  ___XXXXX,XXXXXXX_,________,
  ___X____,______X_,________,
  ___XXXXX,XXXXXXX_,________,
  ___X____,______X_,________,
  ___XXXXX,XXXXXXX_,________,
  ________,________,________,
  XXXXXXXX,XXXXXXXX,XX______,
  ___X____,X_____X_,________,
  ___XXXXX,XXXXXXX_,________,
  ___X____,X_____X_,________,
  ___XXXXX,XXXXXXX_,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,X_______,
  ________,X_______,________,
  XXXXXXXX,XXXXXXXX,XX______};
  
GUI_CONST_STORAGE unsigned char acGUI_FontHZ20S_7CFB[ 32] = { /* code 7CFB */
  ________,__XXXXX_,
  _XXXXXXX,XX______,
  ______XX,________,
  _____XX_,____XX__,
  ____X___,___XX___,
  __XXXXXX,XXXX____,
  _XXX____,XX______,
  _______X,X__X____,
  _____XX_,____X___,
  ____X___,____XXX_,
  __XXXXXX,XXXXXXXX,
  _X______,X_____X_,
  ____X___,X__XX___,
  __XX____,X___XX__,
  _XX_____,X____XX_,
  XX___XXX,X_____XX};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ20S_7EDF[ 51] = { /* code 7EDF */
  ___X____,__X_____,________,
  __XX____,__XX____,________,
  __X_____,___XX___,________,
  __X__XXX,XXXXXXXX,X_______,
  _X______,_XX_____,________,
  XX__X___,XX___X__,________,
  X__X___X,X_____X_,________,
  XXXX__XX,______XX,________,
  __X__XXX,XXXXXXXX,________,
  __X_____,X___X___,X_______,
  _X______,X___X___,________,
  XXXXX___,X___X___,________,
  XX______,X___X___,________,
  ____XX_X,____X___,X_______,
  _XXX___X,____X___,X_______,
  XX___XX_,____X___,X_______,
  ____XX__,____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ20S_7F6E[ 48] = { /* code 7F6E */
  __XXXXXX,XXXXXXXX,________,
  __X___X_,___X___X,________,
  __X___X_,___X___X,________,
  __XXXXXX,XXXXXXXX,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,X_______,
  ________,X_______,________,
  ___XXXXX,XXXXXXX_,________,
  ___X____,______X_,________,
  ___XXXXX,XXXXXXX_,________,
  ___X____,______X_,________,
  ___XXXXX,XXXXXXX_,________,
  ___X____,______X_,________,
  ___XXXXX,XXXXXXX_,________,
  ___X____,______X_,________,
  XXXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ20S_8BBE[ 48] = { /* code 8BBE */
  _X_____X,XXXXXX__,________,
  __X____X,_____X__,________,
  ___X___X,_____X__,________,
  ______XX,_____X__,________,
  _____XX_,_____XXX,X_______,
  XXX__X__,________,________,
  __X_____,________,________,
  __X__XXX,XXXXXXX_,________,
  __X____X,______X_,________,
  __X____X,X____X__,________,
  __X_____,X___XX__,________,
  __X_X___,_X_XX___,________,
  __XXX___,_XXX____,________,
  _XXX____,XX_XX___,________,
  _X___XXX,____XXX_,________,
  ___XXX__,______XX,________};
  
  
GUI_CONST_STORAGE unsigned char acGUI_FontHZ20S_4FE1[ 34] = { /* code 4FE1 */
  ____X___,_X______,
  ___XX___,_XX_____,
  ___X_XXX,XXXXXXXX,
  __X_____,________,
  __X_____,________,
  __X__XXX,XXXXXXX_,
  _XX_____,________,
  XXX_____,________,
  X_X___XX,XXXXXXX_,
  __X_____,________,
  __X_____,________,
  __X___XX,XXXXXXX_,
  __X___X_,______X_,
  __X___X_,______X_,
  __X___X_,______X_,
  __X___XX,XXXXXXX_,
  __X___X_,______X_};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ20S_606F[ 48] = { /* code 606F */
  _______X,________,________,
  _______X,________,________,
  __XXXXXX,XXXXXXX_,________,
  __X_____,______X_,________,
  __XXXXXX,XXXXXXX_,________,
  __X_____,______X_,________,
  __XXXXXX,XXXXXXX_,________,
  __X_____,______X_,________,
  __XXXXXX,XXXXXXX_,________,
  __X_____,______X_,________,
  ________,X_______,________,
  __X_X___,_X_____X,________,
  _X__X___,__X__X__,X_______,
  _X__X___,_____X__,XX______,
  X___X___,____XX__,_X______,
  _____XXX,XXXXX___,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontHZ20S_CharInfo[10] = {
   {  18,  15,   0,   5,  18, acGUI_FontHZ20S_663E } /* code 663E */
  ,{  17,  17,   0,   4,  18, acGUI_FontHZ20S_6D4B } /* code 6D4B */
  ,{  18,  16,   0,   5,  18, acGUI_FontHZ20S_793A } /* code 793A */
  ,{  18,  15,   0,   5,  18, acGUI_FontHZ20S_91CF } /* code 91CF */
  ,{  16,  16,   1,   4,  18, acGUI_FontHZ20S_7CFB } /* code 7CFB */
  ,{  17,  17,   0,   3,  18, acGUI_FontHZ20S_7EDF } /* code 7EDF */
  ,{  18,  16,   0,   5,  18, acGUI_FontHZ20S_7F6E } /* code 7F6E */
  ,{  17,  16,   1,   5,  18, acGUI_FontHZ20S_8BBE } /* code 8BBE */
  ,{  16,  17,   1,   4,  18, acGUI_FontHZ20S_4FE1 } /* code 4FE1 */
  ,{  18,  17,   1,   5,  20, acGUI_FontHZ20S_606F } /* code 606F */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ20S_Prop10 = {
   0x606F /* first character */
  ,0x606F /* last character  */
  ,&GUI_FontHZ20S_CharInfo[  9] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ20S_Prop9 = {
   0x4FE1 /* first character */
  ,0x4FE1 /* last character  */
  ,&GUI_FontHZ20S_CharInfo[  8] /* address of first character */
  ,&GUI_FontHZ20S_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ20S_Prop8 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontHZ20S_CharInfo[  7] /* address of first character */
  ,&GUI_FontHZ20S_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ20S_Prop7 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontHZ20S_CharInfo[  6] /* address of first character */
  ,&GUI_FontHZ20S_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ20S_Prop6 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_FontHZ20S_CharInfo[  5] /* address of first character */
  ,&GUI_FontHZ20S_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ20S_Prop5 = {
   0x7CFB /* first character */
  ,0x7CFB /* last character  */
  ,&GUI_FontHZ20S_CharInfo[  4] /* address of first character */
  ,&GUI_FontHZ20S_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ20S_Prop4 = {
   0x91CF /* first character */
  ,0x91CF /* last character  */
  ,&GUI_FontHZ20S_CharInfo[  3] /* address of first character */
  ,&GUI_FontHZ20S_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ20S_Prop3 = {
   0x793A /* first character */
  ,0x793A /* last character  */
  ,&GUI_FontHZ20S_CharInfo[  2] /* address of first character */
  ,&GUI_FontHZ20S_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ20S_Prop2 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontHZ20S_CharInfo[  1] /* address of first character */
  ,&GUI_FontHZ20S_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ20S_Prop1 = {
   0x663E /* first character */
  ,0x663E /* last character  */
  ,&GUI_FontHZ20S_CharInfo[  0] /* address of first character */
  ,&GUI_FontHZ20S_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHZ20S = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHZ20S_Prop1}
  ,19 /* Baseline */
  ,10 /* Height of lowercase characters */
  ,14 /* Height of capital characters */
};

