/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HZ32.c                                                *
* Font:        ºÚÌå                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        03A9 - 03A9                                  *
* Range enabled:        4E2D - 4E2D                                  *
* Range enabled:        4E3B - 4E3B                                  *
* Range enabled:        4FDD - 4FDD                                  *
* Range enabled:        503C - 503C                                  *
* Range enabled:        505C - 505C                                  *
* Range enabled:        5145 - 5145                                  *
* Range enabled:        5185 - 5185                                  *
* Range enabled:        5217 - 5217                                  *
* Range enabled:        52A8 - 52A8                                  *
* Range enabled:        5355 - 5355                                  *
* Range enabled:        538B - 538B                                  *
* Range enabled:        53D6 - 53D6                                  *
* Range enabled:        53F7 - 53F7                                  *
* Range enabled:        5426 - 5426                                  *
* Range enabled:        59CB - 59CB                                  *
* Range enabled:        5B50 - 5B50                                  *
* Range enabled:        5B58 - 5B58                                  *
* Range enabled:        5B9A - 5B9A                                  *
* Range enabled:        5F00 - 5F00                                  *
* Range enabled:        5F0F - 5F0F                                  *
* Range enabled:        6001 - 6001                                  *
* Range enabled:        62A4 - 62A4                                  *
* Range enabled:        63A7 - 63A7                                  *
* Range enabled:        653E - 653E                                  *
* Range enabled:        6587 - 6587                                  *
* Range enabled:        662F - 662F                                  *
* Range enabled:        679C - 679C                                  *
* Range enabled:        6A21 - 6A21                                  *
* Range enabled:        6B62 - 6B62                                  *
* Range enabled:        6D41 - 6D41                                  *
* Range enabled:        6D4B - 6D4B                                  *
* Range enabled:        6E90 - 6E90                                  *
* Range enabled:        7535 - 7535                                  *
* Range enabled:        786E - 786E                                  *
* Range enabled:        7A0B - 7A0B                                  *
* Range enabled:        7C7B - 7C7B                                  *
* Range enabled:        7CFB - 7CFB                                  *
* Range enabled:        7EBF - 7EBF                                  *
* Range enabled:        7ED3 - 7ED3                                  *
* Range enabled:        7EDF - 7EDF                                  *
* Range enabled:        7F6E - 7F6E                                  *
* Range enabled:        81EA - 81EA                                  *
* Range enabled:        82F1 - 82F1                                  *
* Range enabled:        83DC - 83DC                                  *
* Range enabled:        8868 - 8868                                  *
* Range enabled:        8A00 - 8A00                                  *
* Range enabled:        8BBE - 8BBE                                  *
* Range enabled:        8BD5 - 8BD5                                  *
* Range enabled:        8BED - 8BED                                  *
* Range enabled:        8BFB - 8BFB                                  *
* Range enabled:        8D1F - 8D1F                                  *
* Range enabled:        8F7D - 8F7D                                  *
* Range enabled:        8FC7 - 8FC7                                  *
* Range enabled:        963B - 963B                                  *
* Range enabled:        5173 - 5173                                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHZ32;

/* Start of unicode area <Basic Greek> */
GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_03A9[ 75] = { /* code 03A9, GREEK CAPITAL LETTER OMEGA */
  ________,________,________,
  _______X,XXXXXXXX,________,
  ______XX,XX____XX,XX______,
  ____XXXX,_______X,XXX_____,
  ___XXXX_,________,XXXX____,
  __XXXX__,________,_XXXX___,
  __XXXX__,________,_XXXX___,
  _XXXX___,________,__XXXX__,
  _XXXX___,________,__XXXX__,
  _XXXX___,________,__XXXXX_,
  _XXXX___,________,__XXXXX_,
  _XXXX___,________,__XXXXX_,
  _XXXX___,________,__XXXXX_,
  _XXXX___,________,__XXXX__,
  _XXXX___,________,__XXXX__,
  _XXXX___,________,__XXXX__,
  __XXXX__,________,_XXXX___,
  __XXXX__,________,_XXXX___,
  ___XXXX_,________,XXXX____,
  _____XXX,______XX,XX______,
  _______X,XX___XXX,________,
  _XX_____,XX___XX_,____XX__,
  _XX_____,XX___XX_,____XX__,
  _XXXXXXX,XX___XXX,XXXXXX__,
  _XXXXXXX,XX___XXX,XXXXXX__};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_4E2D[ 87] = { /* code 4E2D */
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXX_____,___XX___,_____XXX,
  XXX_____,___XX___,_____XXX,
  XXX_____,___XX___,_____XXX,
  XXX_____,___XX___,_____XXX,
  XXX_____,___XX___,_____XXX,
  XXX_____,___XX___,_____XXX,
  XXX_____,___XX___,_____XXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXX_____,___XX___,_____XXX,
  XXX_____,___XX___,_____XXX,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,__XXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_4E3B[112] = { /* code 4E3B */
  ________,___X____,________,________,
  ________,__XXX___,________,________,
  ________,___XXX__,________,________,
  ________,____XXX_,________,________,
  ________,____XXXX,________,________,
  ________,_____XX_,________,________,
  ________,_____X__,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_4FDD[116] = { /* code 4FDD */
  _______X,________,________,________,
  ______XX,X___XXXX,XXXXXXXX,XX______,
  ______XX,X___XXXX,XXXXXXXX,XX______,
  ______XX,____XX__,________,XX______,
  _____XXX,____XX__,________,XX______,
  _____XX_,____XX__,________,XX______,
  _____XX_,____XX__,________,XX______,
  ____XXX_,____XX__,________,XX______,
  ____XXX_,____XX__,________,XX______,
  ___XXXX_,____XXXX,XXXXXXXX,XX______,
  __XXXXX_,____XXXX,XXXXXXXX,XX______,
  __XX_XX_,________,__XX____,________,
  _XXX_XX_,________,__XX____,________,
  XXX__XX_,________,__XX____,________,
  _XX__XX_,________,__XX____,________,
  _X___XX_,_XXXXXXX,XXXXXXXX,XXXXX___,
  _____XX_,_XXXXXXX,XXXXXXXX,XXXXX___,
  _____XX_,_______X,X_XXXX__,________,
  _____XX_,______XX,X_XX_XX_,________,
  _____XX_,______XX,__XX_XXX,________,
  _____XX_,_____XXX,__XX__XX,________,
  _____XX_,____XXX_,__XX__XX,X_______,
  _____XX_,___XXX__,__XX___X,XXX_____,
  _____XX_,__XXXX__,__XX____,XXXX____,
  _____XX_,_XXXX___,__XX____,_XXXXX__,
  _____XX_,_XXX____,__XX____,__XXX___,
  _____XX_,__X_____,__XX____,________,
  _____XX_,________,__XX____,________,
  _____XX_,________,__XX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_503C[116] = { /* code 503C */
  _______X,________,________,________,
  _______X,XX______,_XXX____,________,
  ______XX,X_______,_XXX____,________,
  ______XX,X_______,_XXX____,________,
  ______XX,__XXXXXX,XXXXXXXX,XXXX____,
  _____XXX,__XXXXXX,XXXXXXXX,XXXX____,
  _____XXX,________,_XXX____,________,
  ____XXX_,________,_XXX____,________,
  ____XXX_,____XXXX,XXXXXXXX,XX______,
  ___XXXX_,____XXXX,XXXXXXXX,XX______,
  __XXXXX_,____XX__,________,XX______,
  __XXXXX_,____XX__,________,XX______,
  _XXX_XX_,____XX__,________,XX______,
  _XX__XX_,____XXXX,XXXXXXXX,XX______,
  __X__XX_,____XXXX,XXXXXXXX,XX______,
  _____XX_,____XX__,________,XX______,
  _____XX_,____XX__,________,XX______,
  _____XX_,____XXXX,XXXXXXXX,XX______,
  _____XX_,____XXXX,XXXXXXXX,XX______,
  _____XX_,____XX__,________,XX______,
  _____XX_,____XX__,________,XX______,
  _____XX_,____XXXX,XXXXXXXX,XX______,
  _____XX_,____XXXX,XXXXXXXX,XX______,
  _____XX_,____XX__,________,XX______,
  _____XX_,____XX__,________,XX______,
  _____XX_,XXXXXXXX,XXXXXXXX,XXXXXX__,
  _____XX_,XXXXXXXX,XXXXXXXX,XXXXXX__,
  _____XX_,________,________,________,
  _____XX_,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_505C[120] = { /* code 505C */
  ________,________,________,________,
  ______XX,________,_XXX____,________,
  _____XXX,________,__XX____,________,
  _____XXX,________,__XXX___,________,
  _____XX_,__XXXXXX,XXXXXXXX,XXXXX___,
  ____XXX_,__XXXXXX,XXXXXXXX,XXXXX___,
  ____XXX_,________,________,________,
  ____XXX_,____XXXX,XXXXXXXX,XX______,
  ___XXXX_,____XXXX,XXXXXXXX,XX______,
  __XXXXX_,____XX__,________,XX______,
  __XXXXX_,____XX__,________,XX______,
  _XXXXXX_,____XX__,________,XX______,
  _XXXXXX_,____XXXX,XXXXXXXX,XX______,
  XXX_XXX_,____XXXX,XXXXXXXX,XX______,
  _XX_XXX_,________,________,________,
  ____XXX_,XXXXXXXX,XXXXXXXX,XXXXX___,
  ____XXX_,XXXXXXXX,XXXXXXXX,XXXXX___,
  ____XXX_,XXX_____,________,___XX___,
  ____XXX_,XXX_____,________,___XX___,
  ____XXX_,____X___,________,_X______,
  ____XXX_,____XXXX,XXXXXXXX,XX______,
  ____XXX_,____XXXX,XXXXXXXX,XX______,
  ____XXX_,________,__XXX___,________,
  ____XXX_,________,__XXX___,________,
  ____XXX_,________,__XXX___,________,
  ____XXX_,________,__XXX___,________,
  ____XXX_,________,__XXX___,________,
  ____XXX_,_______X,XXXX____,________,
  ____XXX_,_______X,XXXX____,________,
  ____XXX_,________,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_5145[116] = { /* code 5145 */
  ________,_____XX_,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,_____XXX,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,__XX____,________,________,
  ________,_XXXX___,___X____,________,
  ________,XXX_____,__XXX___,________,
  _______X,XX______,___XXX__,________,
  _____XXX,X_______,____XXX_,________,
  ___XXXXX,____XXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXX_,XXX____X,XX______,
  ____X___,_XX_____,XXX____X,X_______,
  ________,_XX_____,XXX_____,________,
  ________,_XX_____,XXX_____,________,
  ________,_XX_____,XXX_____,________,
  ________,XXX_____,XXX_____,________,
  ________,XXX_____,XXX_____,________,
  ________,XX______,XXX_____,________,
  _______X,XX______,XXX_____,_XX_____,
  ______XX,X_______,XXX_____,_XXX____,
  _____XXX,X_______,XXX_____,_XXX____,
  ____XXXX,________,XXX_____,_XXX____,
  __XXXXX_,________,XXXXXXXX,XXX_____,
  _XXXXX__,________,_XXXXXXX,XXX_____,
  __XX____,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_5173[116] = { /* code 5173 */
  ________,X_______,__X_____,________,
  _______X,XX______,__XXX___,________,
  _______X,XX______,__XXX___,________,
  ________,XXX_____,_XXX____,________,
  ________,XXXX____,_XXX____,________,
  ________,_XX_____,XXX_____,________,
  ________,_X______,XXX_____,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,____XXXX,________,________,
  ________,____XXXX,________,________,
  ________,___XXXXX,X_______,________,
  ________,___XXX_X,XX______,________,
  ________,__XXX___,XXX_____,________,
  ________,_XXX____,XXXX____,________,
  ________,XXX_____,_XXXXX__,________,
  ______XX,XX______,__XXXXXX,________,
  ____XXXX,X_______,____XXXX,XXX_____,
  _XXXXXX_,________,_____XXX,XXX_____,
  _XXXXX__,________,_______X,XXX_____,
  __XX____,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_5185[116] = { /* code 5185 */
  ________,____XXX_,________,________,
  ________,____XX__,________,________,
  ________,____XX__,________,________,
  ________,____XX__,________,________,
  ________,____XX__,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXX_____,____XX__,_______X,XX______,
  XXX_____,____XX__,_______X,XX______,
  XXX_____,___XXX__,_______X,XX______,
  XXX_____,___XXX__,_______X,XX______,
  XXX_____,___XXX__,_______X,XX______,
  XXX_____,___XXXX_,_______X,XX______,
  XXX_____,__XXXXXX,_______X,XX______,
  XXX_____,_XXXX_XX,X______X,XX______,
  XXX_____,_XXX___X,XXX____X,XX______,
  XXX_____,XXX_____,XXXX___X,XX______,
  XXX____X,XX______,_XXXX__X,XX______,
  XXX__XXX,XX______,__XXX__X,XX______,
  XXX_XXXX,X_______,___X___X,XX______,
  XXX___XX,________,_______X,XX______,
  XXX_____,________,_______X,XX______,
  XXX_____,________,_______X,XX______,
  XXX_____,________,_______X,XX______,
  XXX_____,________,_______X,XX______,
  XXX_____,________,_______X,XX______,
  XXX_____,________,___XXXXX,XX______,
  XXX_____,________,___XXXXX,X_______,
  XXX_____,________,____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_5217[112] = { /* code 5217 */
  ________,________,________,_XXX____,
  XXXXXXXX,XXXXXXXX,X_______,_XXX____,
  XXXXXXXX,XXXXXXXX,X_______,_XXX____,
  ______XX,X_______,__XXXX__,_XXX____,
  _____XXX,________,___XX___,_XXX____,
  _____XXX,________,___XX___,_XXX____,
  _____XXX,________,___XX___,_XXX____,
  _____XXX,XXXXXXX_,___XX___,_XXX____,
  ____XXXX,XXXXXXX_,___XX___,_XXX____,
  ____XXXX,XXXXXXX_,___XX___,_XXX____,
  ___XXX__,____XXX_,___XX___,_XXX____,
  ___XXX__,____XXX_,___XX___,_XXX____,
  __XXX___,____XX__,___XX___,_XXX____,
  __XXX___,____XX__,___XX___,_XXX____,
  _XXX__XX,___XXX__,___XX___,_XXX____,
  XXXX_XXX,X__XXX__,___XX___,_XXX____,
  _XX___XX,XX_XX___,___XX___,_XXX____,
  ________,XXXXX___,___XX___,_XXX____,
  ________,_XXX____,___XX___,_XXX____,
  ________,_XXX____,___XX___,_XXX____,
  ________,XXX_____,___XX___,_XXX____,
  _______X,XXX_____,________,_XXX____,
  ______XX,XX______,________,_XXX____,
  _____XXX,X_______,________,_XXX____,
  ___XXXXX,________,________,_XXX____,
  _XXXXXX_,________,______XX,XXXX____,
  _XXXX___,________,______XX,XXX_____,
  __XX____,________,______XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_52A8[116] = { /* code 52A8 */
  ________,________,____X___,________,
  ________,________,____XX__,________,
  ________,________,____XX__,________,
  ________,________,____XX__,________,
  __XXXXXX,XXXXXX__,____XX__,________,
  __XXXXXX,XXXXXX__,____XX__,________,
  ________,________,____XX__,________,
  ________,______XX,XXXXXXXX,XXXXX___,
  ________,______XX,XXXXXXXX,XXXXX___,
  ________,________,____XX__,___XX___,
  ________,________,____XX__,___XX___,
  XXXXXXXX,XXXXXXX_,____XX__,___XX___,
  XXXXXXXX,XXXXXXX_,____XX__,__XXX___,
  ______XX,________,____XX__,__XXX___,
  _____XXX,________,___XXX__,__XXX___,
  _____XX_,________,___XXX__,__XXX___,
  _____XX_,___X____,___XXX__,__XXX___,
  ____XXX_,__XXX___,___XX___,__XXX___,
  ____XX__,___XX___,___XX___,__XXX___,
  ___XXX__,___XXX__,___XX___,__XX____,
  ___XX___,____XXX_,__XXX___,__XX____,
  __XXX__X,XXXXXXX_,__XX____,__XX____,
  _XXXXXXX,XXXXXXX_,_XXX____,__XX____,
  __XXXXXX,_____XXX,_XX_____,__XX____,
  __X_____,________,XXX_____,__XX____,
  ________,_______X,XX______,_XXX____,
  ________,______XX,X____XXX,XXXX____,
  ________,_____XXX,______XX,XXX_____,
  ________,______XX,______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_5355[116] = { /* code 5355 */
  ________,X_______,__XX____,________,
  _______X,XX______,__XXX___,________,
  ________,XX______,_XXX____,________,
  ________,XXX_____,_XXX____,________,
  ________,_XX_____,_XX_____,________,
  ________,________,XXX_____,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ____XX__,_____XX_,______XX,________,
  ____XX__,_____XX_,______XX,________,
  ____XX__,_____XX_,______XX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ____XX__,_____XX_,______XX,________,
  ____XX__,_____XX_,______XX,________,
  ____XX__,_____XX_,______XX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,____XXX_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_538B[112] = { /* code 538B */
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ____XX__,________,________,________,
  ____XX__,_______X,XX______,________,
  ____XX__,_______X,XX______,________,
  ____XX__,_______X,XX______,________,
  ____XX__,_______X,XX______,________,
  ____XX__,_______X,XX______,________,
  ____XX__,_______X,XX______,________,
  ____XX__,_______X,XX______,________,
  ____XX__,XXXXXXXX,XXXXXXXX,XX______,
  ____XX__,XXXXXXXX,XXXXXXXX,XX______,
  ____XX__,XXXXXXXX,XXXXXXXX,XX______,
  ____XX__,_______X,XX______,________,
  ____XX__,_______X,XX______,________,
  ____XX__,_______X,XX___XX_,________,
  ___XXX__,_______X,XX__XXX_,________,
  ___XXX__,_______X,XX___XXX,________,
  ___XXX__,_______X,XX____XX,X_______,
  ___XXX__,_______X,XX____XX,X_______,
  ___XX___,_______X,XX______,________,
  __XXX___,_______X,XX______,________,
  __XXX___,_______X,XX______,________,
  _XXX__XX,XXXXXXXX,XXXXXXXX,XXXX____,
  _XXX__XX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXX___XX,XXXXXXXX,XXXXXXXX,XXXX____,
  __X_____,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_53D6[116] = { /* code 53D6 */
  ________,________,________,________,
  XXXXXXXX,XXXXXXX_,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XX___,___XX__X,XXXXXXXX,XXX_____,
  ___XX___,___XX___,_XX_____,XXX_____,
  ___XX___,___XX___,_XX_____,XXX_____,
  ___XX___,___XX___,_XX_____,XXX_____,
  ___XX___,___XX___,_XX_____,XX______,
  ___XXXXX,XXXXX___,_XX_____,XX______,
  ___XXXXX,XXXXX___,_XX_____,XX______,
  ___XX___,___XX___,_XX____X,XX______,
  ___XX___,___XX___,_XX____X,XX______,
  ___XX___,___XX___,_XXX___X,X_______,
  ___XX___,___XX___,__XX___X,X_______,
  ___XXXXX,XXXXX___,__XX__XX,X_______,
  ___XXXXX,XXXXX___,__XXX_XX,________,
  ___XX___,___XX___,__XXXXXX,________,
  ___XX___,___XX___,___XXXXX,________,
  ___XX___,___XX___,___XXXX_,________,
  ___XX___,___XXXXX,____XXX_,________,
  ___XX___,XXXXXXXX,___XXXX_,________,
  ___XXXXX,XXXXX___,__XXXXXX,________,
  XXXXXXXX,___XX___,_XXXX_XX,X_______,
  XXXXX___,___XX___,_XXX___X,XXX_____,
  _X______,___XX__X,XXX_____,XXXX____,
  ________,___XX_XX,XX______,_XXXX___,
  ________,___XX__X,X_______,__X_____,
  ________,___XX___,________,________,
  ________,__XXX___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_53F7[112] = { /* code 53F7 */
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,________,_____XX_,________,
  _____XXX,________,_____XX_,________,
  _____XXX,________,_____XX_,________,
  _____XXX,________,_____XX_,________,
  _____XXX,________,_____XX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,XX______,________,________,
  _______X,XX______,________,________,
  _______X,X_______,________,________,
  _______X,X_______,________,________,
  ______XX,XXXXXXXX,XXXXXXXX,________,
  ______XX,XXXXXXXX,XXXXXXXX,________,
  ________,________,_____XX_,________,
  ________,________,_____XX_,________,
  ________,________,____XXX_,________,
  ________,________,____XXX_,________,
  ________,________,____XXX_,________,
  ________,_____XXX,XXXXXX__,________,
  ________,_____XXX,XXXXXX__,________,
  ________,______XX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_5426[108] = { /* code 5426 */
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,______XX,X_______,________,
  ________,_____XXX,________,________,
  ________,____XXXX,________,________,
  ________,___XXXXX,___X____,________,
  ________,_XXXXXXX,___XXX__,________,
  ________,XXXX_XXX,__XXXXXX,________,
  ______XX,XXX__XXX,____XXXX,XX______,
  ____XXXX,XX___XXX,______XX,XXXX____,
  __XXXXXX,_____XXX,_______X,XXXXX___,
  _XXXXX__,_____XXX,________,_XXXX___,
  __XX____,_____XXX,________,___X____,
  ________,_____XXX,________,________,
  _____XXX,XXXXXXXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,XXXXXXXX,X_______,
  _____XXX,________,______XX,X_______,
  _____XXX,________,______XX,X_______,
  _____XXX,________,______XX,X_______,
  _____XXX,________,______XX,X_______,
  _____XXX,________,______XX,X_______,
  _____XXX,XXXXXXXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,XXXXXXXX,X_______,
  _____XXX,________,______XX,X_______,
  _____XXX,________,______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_59CB[116] = { /* code 59CB */
  _____XX_,________,__X_____,________,
  _____XX_,________,__XXX___,________,
  _____XX_,________,_XXX____,________,
  _____XX_,________,_XXX____,________,
  ____XXX_,________,XXX_____,________,
  ____XXX_,________,XX______,X_______,
  ____XX__,_______X,XX____XX,X_______,
  _XXXXXXX,XXXX___X,X______X,XX______,
  _XXXXXXX,XXXX__XX,________,XXX_____,
  ____XX__,_XX__XXX,________,_XXX____,
  ___XXX__,_XX_XXXX,XXXXXXXX,XXXXX___,
  ___XX___,_XX__XXX,XXXXXXXX,XXXXX___,
  ___XX___,_XX__XXX,________,___XX___,
  ___XX___,_XX_____,________,________,
  __XXX___,XXX_____,________,________,
  __XXX___,XX______,________,________,
  __XX____,XX____XX,XXXXXXXX,XXXX____,
  __XXX__X,XX____XX,XXXXXXXX,XXXX____,
  __XXXX_X,XX____XX,________,_XXX____,
  ____XXXX,X_____XX,________,_XXX____,
  _____XXX,X_____XX,________,_XXX____,
  ______XX,XX____XX,________,_XXX____,
  _____XXX,XXX___XX,________,_XXX____,
  ____XXX_,_XXX__XX,________,_XXX____,
  ____XXX_,__XX__XX,XXXXXXXX,XXXX____,
  ___XXX__,______XX,XXXXXXXX,XXXX____,
  __XXX___,______XX,XXXXXXXX,XXXX____,
  _XXX____,______XX,________,_XXX____,
  __X_____,______XX,________,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_5B50[108] = { /* code 5B50 */
  ___XXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,________,____XXXX,________,
  ________,________,__XXXX__,________,
  ________,________,XXXX____,________,
  ________,_______X,XXX_____,________,
  ________,_____XXX,X_______,________,
  ________,_____XXX,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,____XXX_,________,________,
  ________,_XXXXXX_,________,________,
  ________,_XXXXXX_,________,________,
  ________,_XXX____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_5B58[116] = { /* code 5B58 */
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,____XX__,________,________,
  ________,___XXX__,________,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,__XXX___,________,________,
  ________,__XX____,________,________,
  ________,_XXX____,________,________,
  ________,XXX_____,________,________,
  ______XX,XX__XXXX,XXXXXXXX,XXX_____,
  ______XX,XX__XXXX,XXXXXXXX,XXX_____,
  ______XX,X_______,_______X,XXX_____,
  _____XXX,________,______XX,XX______,
  ____XXXX,________,____XXXX,________,
  ___XXXXX,________,___XXX__,________,
  __XXX_XX,________,___XX___,________,
  _XXX__XX,________,___XX___,________,
  __X___XX,__XXXXXX,XXXXXXXX,XXXXX___,
  ______XX,__XXXXXX,XXXXXXXX,XXXXX___,
  ______XX,________,___XX___,________,
  ______XX,________,___XX___,________,
  ______XX,________,___XX___,________,
  ______XX,________,___XX___,________,
  ______XX,________,___XX___,________,
  ______XX,________,___XX___,________,
  ______XX,________,__XXX___,________,
  ______XX,________,XXXXX___,________,
  ______XX,________,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_5B9A[120] = { /* code 5B9A */
  ________,______X_,________,________,
  ________,_____XX_,________,________,
  ________,_____XXX,________,________,
  ________,_____XXX,X_______,________,
  ________,______XX,________,________,
  ________,______X_,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ___XX___,________,________,_XXX____,
  ___XX___,________,________,_XXX____,
  ___XX___,________,________,_XXX____,
  ______XX,XXXXXXXX,XXXXXXXX,X_______,
  ______XX,XXXXXXXX,XXXXXXXX,X_______,
  ______XX,XXXXXXXX,XXXXXXXX,X_______,
  ________,______XX,X_______,________,
  ________,______XX,X_______,________,
  _______X,______XX,X_______,________,
  _______X,XX____XX,X_______,________,
  ______XX,X_____XX,XXXXXXXX,XX______,
  ______XX,X_____XX,XXXXXXXX,XX______,
  ______XX,______XX,XXXXXXXX,XX______,
  _____XXX,______XX,X_______,________,
  _____XXX,X_____XX,X_______,________,
  ____XXXX,XX____XX,X_______,________,
  ___XXX__,XXX___XX,X_______,________,
  ___XXX__,_XXXX_XX,X_______,________,
  __XXX___,__XXXXXX,X_______,____X___,
  _XXX____,____XXXX,XXXXXXXX,XXXXX___,
  XXXX____,______XX,XXXXXXXX,XXXX____,
  __X_____,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_5F00[112] = { /* code 5F00 */
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,_XXX____,__XXX___,________,
  ________,_XXX____,__XXX___,________,
  ________,_XXX____,__XXX___,________,
  ________,_XXX____,__XXX___,________,
  ________,_XXX____,__XXX___,________,
  ________,_XXX____,__XXX___,________,
  ________,_XXX____,__XXX___,________,
  ________,_XXX____,__XXX___,________,
  ________,_XXX____,__XXX___,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,_XXX____,__XXX___,________,
  ________,_XX_____,__XXX___,________,
  ________,XXX_____,__XXX___,________,
  ________,XXX_____,__XXX___,________,
  ________,XXX_____,__XXX___,________,
  _______X,XX______,__XXX___,________,
  _______X,XX______,__XXX___,________,
  ______XX,X_______,__XXX___,________,
  _____XXX,X_______,__XXX___,________,
  ____XXXX,________,__XXX___,________,
  ___XXXX_,________,__XXX___,________,
  _XXXXX__,________,__XXX___,________,
  __XXX___,________,__XXX___,________,
  ___X____,________,__XXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_5F0F[116] = { /* code 5F0F */
  ________,______XX,X_______,________,
  ________,______XX,X___XX__,________,
  ________,______XX,X___XXX_,________,
  ________,______XX,X____XXX,________,
  ________,______XX,X____XXX,X_______,
  ________,______XX,X_____X_,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,_______X,X_______,________,
  ________,_______X,XX______,________,
  ________,_______X,XX______,________,
  ________,_______X,XX______,________,
  _XXXXXXX,XXXXXX__,XX______,________,
  _XXXXXXX,XXXXXX__,XX______,________,
  ______XX,X_______,XXX_____,________,
  ______XX,X_______,XXX_____,________,
  ______XX,X_______,_XX_____,________,
  ______XX,X_______,_XXX____,________,
  ______XX,X_______,_XXX____,________,
  ______XX,X_______,__XX____,________,
  ______XX,X_______,__XXX___,________,
  ______XX,X___XXX_,___XXX__,__XX____,
  ______XX,XXXXXXX_,___XXX__,__XXX___,
  ___XXXXX,XXXX____,____XXX_,_XXX____,
  _XXXXXXX,________,____XXXX,_XXX____,
  _XXXX___,________,_____XXX,XXXX____,
  _X______,________,______XX,XXX_____,
  ________,________,________,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_6001[112] = { /* code 6001 */
  ________,_____XXX,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,___XX___,_XX_____,________,
  ________,__XXX___,_XXX____,________,
  ________,_XXX____,__XX____,________,
  ________,XXXX____,__XXX___,________,
  _______X,XXX_X___,___XXX__,________,
  ______XX,XX_XXXX_,____XXXX,________,
  _____XXX,X___XXXX,_____XXX,XX______,
  ___XXXXX,_____XXX,______XX,XXXXX___,
  _XXXXX__,______X_,________,XXXX____,
  __XXX___,________,________,__XX____,
  __X_____,________,________,________,
  ________,______XX,X_______,________,
  ___X____,_XXX__XX,X______X,XX______,
  ___XXX__,_XXX___X,XX_____X,XX______,
  ___XXX__,_XXX___X,XX______,XXX_____,
  ___XX___,_XXX____,________,_XXX____,
  __XXX___,_XXX____,_____X__,__XXX___,
  __XX____,_XXX____,_____XXX,__XXX___,
  _XXX____,_XXX____,____XXX_,___X____,
  _XXX____,_XXXXXXX,XXXXXXX_,________,
  ________,_XXXXXXX,XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_62A4[116] = { /* code 62A4 */
  ______XX,________,___XXX__,________,
  ______XX,________,___XXX__,________,
  ______XX,________,____XXX_,________,
  ______XX,________,____XXX_,________,
  ______XX,________,____X___,________,
  ______XX,______XX,XXXXXXXX,XXXXX___,
  ______XX,_______X,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXX__X,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXX__X,X_______,__XXX___,
  ______XX,_______X,X_______,__XXX___,
  ______XX,_______X,X_______,__XXX___,
  ______XX,_______X,X_______,__XXX___,
  ______XX,_______X,X_______,__XXX___,
  ______XX,____X__X,X_______,__XXX___,
  ______XX,XXXXX__X,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXX___X,XXXXXXXX,XXXXX___,
  _XXXXXXX,______XX,X_______,__XXX___,
  _XXX__XX,______XX,X_______,__XXX___,
  ______XX,______XX,X_______,________,
  ______XX,______XX,________,________,
  ______XX,______XX,________,________,
  ______XX,______XX,________,________,
  ______XX,_____XXX,________,________,
  ______XX,_____XXX,________,________,
  ______XX,____XXX_,________,________,
  ______XX,____XXX_,________,________,
  ___XXXXX,___XXX__,________,________,
  ___XXXX_,__XXXX__,________,________,
  ___XX___,___XX___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_63A7[116] = { /* code 63A7 */
  ____XXX_,________,__XX____,________,
  ____XXX_,________,__XXX___,________,
  ____XXX_,________,__XXX___,________,
  ____XXX_,________,__XXX___,________,
  ____XXX_,___XXXXX,XXXXXXXX,XXXXX___,
  ____XXX_,___XXXXX,XXXXXXXX,XXXXX___,
  ____XXX_,___XX___,________,___XX___,
  _XXXXXXX,XX_XX___,________,___XX___,
  _XXXXXXX,XX_XX___,XX____XX,___XX___,
  ____XXX_,_______X,XXX___XX,X_______,
  ____XXX_,______XX,XX_____X,XX______,
  ____XXX_,_____XXX,X_______,XXX_____,
  ____XXX_,_____XXX,________,XXXX____,
  ____XXX_,_X_XXXX_,________,_XXX____,
  ____XXXX,XX__XX__,________,__X_____,
  ____XXXX,XX__X___,________,________,
  _XXXXXX_,____XXXX,XXXXXXXX,XXX_____,
  _XXXXXX_,____XXXX,XXXXXXXX,XXX_____,
  _XX_XXX_,________,___XX___,________,
  ____XXX_,________,___XX___,________,
  ____XXX_,________,___XX___,________,
  ____XXX_,________,___XX___,________,
  ____XXX_,________,___XX___,________,
  ____XXX_,________,___XX___,________,
  ____XXX_,________,___XX___,________,
  ____XXX_,__X_____,___XX___,____XX__,
  __XXXXX_,__XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXX__,__XXXXXX,XXXXXXXX,XXXXXX__,
  __XXX___,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_653E[116] = { /* code 653E */
  _____XX_,________,___XX___,________,
  _____XXX,________,__XXX___,________,
  ______XX,________,__XXX___,________,
  ______XX,X_______,__XX____,________,
  _______X,X_______,__XX____,________,
  ______X_,________,_XXX____,________,
  _XXXXXXX,XXXXXXX_,_XXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXX_,_XXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXX_,XXXXXXXX,XXXXX___,
  _____XX_,________,XX______,XX______,
  _____XX_,_______X,XX______,XX______,
  _____XX_,_______X,XXX_____,XX______,
  _____XX_,______XX,XXX_____,XX______,
  _____XXX,XXXXXX_X,_XXX___X,XX______,
  _____XXX,XXXXXX__,_XXX___X,XX______,
  _____XX_,___XXX__,__XX___X,XX______,
  _____XX_,___XXX__,__XX___X,X_______,
  ____XXX_,___XXX__,__XXX__X,X_______,
  ____XXX_,___XXX__,___XX_XX,X_______,
  ____XX__,___XX___,___XXXXX,X_______,
  ____XX__,___XX___,___XXXXX,________,
  ___XXX__,___XX___,____XXXX,________,
  ___XXX__,___XX___,____XXX_,________,
  ___XX___,___XX___,___XXXXX,________,
  __XXX___,___XX___,__XXX_XX,X_______,
  _XXX____,_XXXX___,_XXX___X,XXX_____,
  _XXX___X,XXXXX_XX,XXX_____,XXXXX___,
  XXX_____,XXXX_XXX,XX______,_XXXX___,
  __X_____,_______X,________,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_6587[116] = { /* code 6587 */
  ________,___XX___,________,________,
  ________,__XXX___,________,________,
  ________,___XXX__,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,_____XX_,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ______XX,________,__XXX___,________,
  ______XX,________,__XXX___,________,
  ______XX,X_______,__XXX___,________,
  _______X,X_______,__XX____,________,
  _______X,X_______,_XXX____,________,
  _______X,XX______,_XXX____,________,
  ________,XX______,XXX_____,________,
  ________,XXX_____,XXX_____,________,
  ________,_XX____X,XX______,________,
  ________,_XXX___X,XX______,________,
  ________,__XXX_XX,X_______,________,
  ________,___XXXXX,________,________,
  ________,____XXX_,________,________,
  ________,___XXXXX,X_______,________,
  ________,_XXXX_XX,XX______,________,
  _______X,XXXX____,XXXX____,________,
  _____XXX,XX______,_XXXXXX_,________,
  __XXXXXX,X_______,___XXXXX,XXXX____,
  XXXXXXX_,________,_____XXX,XXX_____,
  _XXX____,________,________,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_662F[112] = { /* code 662F */
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XX_,________,_____XX_,________,
  _____XX_,________,_____XX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XX_,________,_____XX_,________,
  _____XX_,________,_____XX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,_____XX_,________,________,
  ______XX,_____XX_,________,________,
  ______XX,_____XX_,________,________,
  _____XXX,_____XXX,XXXXXXXX,X_______,
  _____XXX,_____XXX,XXXXXXXX,X_______,
  ____XXXX,X____XX_,________,________,
  ____XXXX,XX___XX_,________,________,
  ___XXX__,XXXX_XX_,________,________,
  __XXXX__,_XXXXXX_,________,____X___,
  _XXXX___,___XXXXX,XXXXXXXX,XXXX____,
  XXXX____,_____XXX,XXXXXXXX,XXXX____,
  _XX_____,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_679C[112] = { /* code 679C */
  ____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XX__,_____XX_,______XX,X_______,
  ____XX__,_____XX_,______XX,X_______,
  ____XX__,_____XX_,______XX,X_______,
  ____XX__,_____XX_,______XX,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XX__,_____XX_,______XX,X_______,
  ____XX__,_____XX_,______XX,X_______,
  ____XX__,_____XX_,______XX,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,__XX_XX_,_XX_____,________,
  ________,_XXX_XX_,_XXX____,________,
  ________,XXX__XX_,__XXX___,________,
  ______XX,XX___XX_,__XXXX__,________,
  _____XXX,X____XX_,___XXXXX,________,
  ___XXXXX,_____XX_,____XXXX,XX______,
  XXXXXX__,_____XX_,______XX,XXXX____,
  _XXXX___,_____XX_,________,XXX_____,
  _XX_____,_____XX_,________,__X_____,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_6A21[116] = { /* code 6A21 */
  _____XX_,________,XX____XX,________,
  _____XX_,________,XX____XX,________,
  _____XX_,________,XX____XX,________,
  _____XX_,___XXXXX,XXXXXXXX,XXXXX___,
  _____XX_,___XXXXX,XXXXXXXX,XXXXX___,
  _____XX_,________,XX____XX,________,
  _____XX_,________,XX____XX,________,
  _XXXXXXX,XXX_____,________,________,
  _XXXXXXX,XXX__XXX,XXXXXXXX,XXX_____,
  _____XX_,_____XX_,________,_XX_____,
  ____XXX_,_____XX_,________,_XX_____,
  ____XXX_,_____XX_,________,_XX_____,
  ____XXX_,X____XXX,XXXXXXXX,XXX_____,
  ___XXXXX,XX___XX_,________,_XX_____,
  ___XXXX_,XXX__XX_,________,_XX_____,
  __XXXXX_,_XX__XX_,________,_XX_____,
  __XX_XX_,_XXX_XXX,XXXXXXXX,XXX_____,
  _XXX_XX_,________,___XX___,________,
  XXX__XX_,________,___XX___,________,
  _XX__XX_,________,__XXX___,________,
  _____XX_,___XXXXX,XXXXXXXX,XXXXX___,
  _____XX_,___XXXXX,XXXXXXXX,XXXXX___,
  _____XX_,________,__XX_XX_,________,
  _____XX_,________,_XX__XXX,________,
  _____XX_,________,XXX___XX,X_______,
  _____XX_,______XX,XX_____X,XX______,
  _____XX_,____XXXX,________,XXXX____,
  _____XX_,__XXXXX_,________,_XXXX___,
  _____XX_,___XX___,________,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_6B62[104] = { /* code 6B62 */
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ____XXX_,______XX,________,________,
  _____XX_,______XX,________,________,
  _____XX_,______XX,________,________,
  _____XX_,______XX,XXXXXXXX,XX______,
  _____XX_,______XX,XXXXXXXX,XX______,
  _____XX_,______XX,________,________,
  _____XX_,______XX,________,________,
  _____XX_,______XX,________,________,
  _____XX_,______XX,________,________,
  _____XX_,______XX,________,________,
  _____XX_,______XX,________,________,
  _____XX_,______XX,________,________,
  _____XX_,______XX,________,________,
  _____XX_,______XX,________,________,
  _____XX_,______XX,________,________,
  _____XX_,______XX,________,________,
  _____XX_,______XX,________,________,
  _____XX_,______XX,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_6D41[120] = { /* code 6D41 */
  ________,________,X_______,________,
  __X_____,_______X,XX______,________,
  __XXX___,________,XX______,________,
  __XXXX__,________,XXX_____,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _____XX_,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,______XX,________,________,
  ________,_____XXX,________,________,
  ________,_____XX_,____XX__,________,
  _X______,____XXX_,____XXX_,________,
  XXXX____,___XXX__,_____XXX,________,
  _XXXX___,__XXX___,______XX,X_______,
  __XXXXX_,_XXXXXXX,XXXXXXXX,XX______,
  ____XX__,_XXXXXXX,XXXXXX_X,XX______,
  ________,_XX_____,________,XXX_____,
  ________,________,________,________,
  _____X__,___XXX_X,XX___XX_,________,
  _____XX_,___XX__X,XX___XX_,________,
  ____XXX_,___XX__X,XX___XX_,________,
  ____XXX_,___XX__X,XX___XX_,________,
  ___XXX__,___XX__X,XX___XX_,________,
  ___XXX__,___XX__X,XX___XX_,________,
  __XXX___,__XXX__X,XX___XX_,________,
  __XXX___,__XXX__X,XX___XX_,__X_____,
  _XXX____,__XX___X,XX___XX_,__XXX___,
  XXXX____,_XXX___X,XX___XX_,__XXX___,
  XXX_____,XXX____X,XX___XXX,XXXX____,
  _XX___XX,XX_____X,XX___XXX,XXXX____,
  _______X,X______X,XX_____X,XX______,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_6D4B[112] = { /* code 6D4B */
  __XX____,________,________,__XX____,
  _XXXX___,_XXXXXXX,XXX_____,__XX____,
  ___XXXX_,_XXXXXXX,XXX_____,__XX____,
  ____XXX_,_XX_____,_XX_____,__XX____,
  _____X__,_XX_____,_XX__XXX,__XX____,
  ________,_XX_____,_XX__XXX,__XX____,
  ________,_XX__XX_,_XX__XXX,__XX____,
  ________,_XX__XX_,_XX__XXX,__XX____,
  _XX_____,_XX__XX_,_XX__XXX,__XX____,
  _XXXX___,_XX__XX_,_XX__XXX,__XX____,
  __XXXX__,_XX__XX_,_XX__XXX,__XX____,
  ___XXX__,_XX__XX_,_XX__XXX,__XX____,
  ____X___,_XX__XX_,_XX__XXX,__XX____,
  ________,_XX__XX_,_XX__XXX,__XX____,
  ________,_XX__XX_,_XX__XXX,__XX____,
  _____X__,_XX__XX_,_XX__XXX,__XX____,
  _____XX_,_XX_XXX_,_XX__XXX,__XX____,
  ____XXX_,_XX_XXX_,_XX__XXX,__XX____,
  ____XXX_,____XX__,_____XXX,__XX____,
  ___XXX__,____XX__,_____XXX,__XX____,
  ___XXX__,___XXX_X,X____XXX,__XX____,
  __XXX___,___XXXXX,XX______,__XX____,
  __XXX___,__XXX__X,XX______,__XX____,
  _XXX____,__XXX___,XXX_____,__XX____,
  XXXX____,_XXX____,_XXX____,__XX____,
  _XX_____,XXX_____,_XXX___X,XXXX____,
  __X____X,XXX_____,__X____X,XXXX____,
  ________,_X______,________,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_6E90[120] = { /* code 6E90 */
  ___X____,________,________,________,
  __XXX___,_XXXXXXX,XXXXXXXX,XXXXX___,
  __XXXX__,_XXXXXXX,XXXXXXXX,XXXXX___,
  ___XXXX_,_XXX____,________,________,
  _____XXX,_XXX____,__XXX___,________,
  ______X_,_XXX____,__XXX___,________,
  ________,_XXX____,__XX____,________,
  ________,_XXX__XX,XXXXXXXX,XXX_____,
  _XX_____,_XXX__XX,XXXXXXXX,XXX_____,
  _XXXX___,_XXX__XX,X_______,_XX_____,
  __XXXX__,_XXX__XX,X_______,_XX_____,
  ___XXXX_,_XXX__XX,XXXXXXXX,XXX_____,
  _____X__,_XXX__XX,XXXXXXXX,XXX_____,
  ________,_XXX__XX,XXXXXXXX,XXX_____,
  ________,_XXX__XX,X_______,_XX_____,
  ________,_XXX__XX,X_______,_XX_____,
  ____XX__,_XXX__XX,XXXXXXXX,XXX_____,
  ____XXX_,_XXX__XX,XXXXXXXX,XXX_____,
  ____XX__,_XXX____,___XXX__,________,
  ___XXX__,_XX_____,___XXX__,________,
  ___XXX__,_XX_____,___XXX__,_X______,
  ___XX___,XXX___XX,___XXX__,XXX_____,
  __XXX___,XXX__XXX,X__XXX__,XXX_____,
  __XXX___,XX___XXX,___XXX__,_XXX____,
  _XXX___X,XX__XXX_,___XXX__,__XXX___,
  _XXX__XX,X__XXX__,___XXX__,___XXX__,
  XXXX_XXX,X_XXXX__,___XXX__,___XX___,
  __X___XX,____X___,_XXXXX__,________,
  _______X,________,__XXX___,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_7535[116] = { /* code 7535 */
  ________,__XXX___,________,________,
  ________,__XXX___,________,________,
  ________,__XXX___,________,________,
  ________,__XXX___,________,________,
  ________,__XXX___,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  XXX_____,__XXX___,____XXX_,________,
  XXX_____,__XXX___,____XXX_,________,
  XXX_____,__XXX___,____XXX_,________,
  XXX_____,__XXX___,____XXX_,________,
  XXX_____,__XXX___,____XXX_,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  XXX_____,__XXX___,____XXX_,________,
  XXX_____,__XXX___,____XXX_,________,
  XXX_____,__XXX___,____XXX_,________,
  XXX_____,__XXX___,____XXX_,________,
  XXX_____,__XXX___,____XXX_,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  XXX_____,__XXX___,________,________,
  XXX_____,__XXX___,________,________,
  XXX_____,__XXX___,________,________,
  ________,__XXX___,________,_XXX____,
  ________,__XXX___,________,XXX_____,
  ________,__XXXX__,________,XXX_____,
  ________,___XXXXX,XXXXXXXX,XXX_____,
  ________,____XXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_786E[120] = { /* code 786E */
  ________,________,________,________,
  ________,________,_XXX____,________,
  ________,________,XXX_____,________,
  ________,________,XX______,________,
  __XXXXXX,XXXX___X,XXXXXXXX,XX______,
  __XXXXXX,XXXX__XX,XXXXXXXX,X_______,
  _____XXX,______XX,X_____XX,________,
  _____XXX,_____XXX,_____XXX,________,
  _____XX_,____XXX_,_____XX_,________,
  _____XX_,___XXX__,____XXX_,________,
  ____XXX_,______XX,XXXXXXXX,XXXXX___,
  ____XX__,______XX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXX__XX,X___XX__,__XXX___,
  ___XXXXX,XXXX__XX,X___XX__,__XXX___,
  __XXXX__,_XXX__XX,X___XX__,__XXX___,
  _XXXXX__,_XXX__XX,XXXXXXXX,XXXXX___,
  _XXXXX__,_XXX__XX,XXXXXXXX,XXXXX___,
  _XX_XX__,_XXX__XX,X___XX__,__XXX___,
  ____XX__,_XXX__XX,X___XX__,__XXX___,
  ____XX__,_XXX__XX,X___XX__,__XXX___,
  ____XX__,_XXX__XX,XXXXXXXX,XXXXX___,
  ____XX__,_XXX__XX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXX__XX,____XX__,__XXX___,
  ____XXXX,XXXX__XX,____XX__,__XXX___,
  ____XX__,_XXX__XX,____XX__,__XXX___,
  ____XX__,_XXX_XXX,____XX__,__XXX___,
  ____XX__,_____XX_,____XX__,__XXX___,
  ____XX__,____XXX_,____XX__,__XXX___,
  ___XXX__,___XXX__,____XX__,XXXXX___,
  ________,________,________,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_7A0B[116] = { /* code 7A0B */
  ________,XXX_____,________,________,
  ____XXXX,XXX___XX,XXXXXXXX,XXXX____,
  _XXXXXXX,XX____XX,XXXXXXXX,XXXX____,
  __XXX_XX,______XX,X_______,_XXX____,
  ______XX,______XX,X_______,_XXX____,
  ______XX,______XX,X_______,_XXX____,
  ______XX,______XX,X_______,_XXX____,
  ______XX,______XX,X_______,_XXX____,
  ______XX,______XX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXX__XX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,________,________,
  ______XX,________,________,________,
  _____XXX,________,________,________,
  _____XXX,_____XXX,XXXXXXXX,XXXXX___,
  ____XXXX,__X__XXX,XXXXXXXX,XXXXX___,
  ____XXXX,_XX__XXX,XXXXXXXX,XXXXX___,
  ___XXXXX,_XXX____,____XX__,________,
  ___XX_XX,__XXX___,____XX__,________,
  __XXX_XX,__XXX___,____XX__,________,
  _XXX__XX,___X__XX,XXXXXXXX,XXXX____,
  XXXX__XX,______XX,XXXXXXXX,XXXX____,
  _XX___XX,______XX,XXXXXXXX,XXXX____,
  ______XX,________,____XX__,________,
  ______XX,________,____XX__,________,
  ______XX,________,____XX__,________,
  ______XX,________,____XX__,________,
  ______XX,____XXXX,XXXXXXXX,XXXXXX__,
  ______XX,____XXXX,XXXXXXXX,XXXXXX__,
  ______XX,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_7C7B[120] = { /* code 7C7B */
  ________,_____XXX,________,________,
  ______X_,_____XXX,_____XXX,________,
  _____XXX,_____XXX,____XXXX,________,
  ______XX,X____XXX,____XXX_,________,
  _______X,XX___XXX,___XXX__,________,
  ________,XX___XXX,__XXX___,________,
  ________,X____XXX,___X____,___X____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,__XXXXXX,__XX____,________,
  ________,_XXX_XXX,_XXXX___,________,
  ________,XXX__XXX,___XXXX_,________,
  ______XX,XX___XXX,____XXXX,________,
  ____XXXX,X____XXX,_____XXX,XX______,
  __XXXXX_,_____XXX,_______X,XXX_____,
  __XXX___,_____XX_,________,XX______,
  __X_____,_____XXX,________,________,
  ________,_____XXX,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,____XXXX,X_______,________,
  ________,____XX_X,X_______,________,
  ________,___XXX__,XX______,________,
  ________,__XXX___,XXXX____,________,
  ________,_XXX____,__XXX___,________,
  _______X,XXX_____,___XXXXX,________,
  ____XXXX,XX______,____XXXX,XXX_____,
  _XXXXXXX,________,______XX,XXXX____,
  _XXXX___,________,________,XXX_____,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_7CFB[116] = { /* code 7CFB */
  ________,________,______XX,X_______,
  ________,________,_XXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,________,________,
  ________,___XXXX_,________,________,
  ________,___XXX__,________,________,
  ________,__XXX___,____XX__,________,
  ________,_XXX____,__XXXXXX,________,
  _______X,XXX_____,_XXXX___,________,
  ____XXXX,X_______,XXXX____,________,
  _____XXX,XXXXXXXX,XX______,________,
  _____XXX,XXXXXXXX,________,________,
  ________,___XXXX_,____XX__,________,
  ________,_XXXX___,____XXXX,________,
  _______X,XXX_____,_____XXX,X_______,
  ____XXXX,XX______,______XX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXX___,XXXX____,
  ________,______XX,________,_XX_____,
  ________,______XX,________,________,
  ______X_,______XX,_____X__,________,
  _____XXX,X_____XX,____XXXX,________,
  ____XXXX,______XX,_____XXX,X_______,
  ___XXX__,______XX,______XX,XX______,
  __XXX___,______XX,_______X,XXX_____,
  XXXX____,______XX,________,XXXX____,
  _XX_____,__XXXXXX,________,_XX_____,
  ________,__XXXXXX,________,________,
  ________,___XX___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_7EBF[120] = { /* code 7EBF */
  ________,________,X_______,________,
  _____XXX,________,XXX_____,________,
  _____XXX,________,XXX__XXX,________,
  _____XX_,________,XXX___XX,________,
  ____XX__,________,XXX___XX,X_______,
  ____XX__,________,XXX____X,________,
  ___XX___,_XX_____,XXX_____,__X_____,
  __XXX___,XXXX____,XXX___XX,XXXX____,
  _XXX____,XXX_____,XXXXXXXX,XXXX____,
  XXX____X,XX_XXXXX,XXXXX___,________,
  XXXXXXXX,X___XXXX,XXX_____,________,
  _XXXXXXX,X_______,_XX_____,____X___,
  ______XX,________,_XX_____,_XXXX___,
  _____XX_,________,_XXXXXXX,XXXXX___,
  _____XX_,_____XXX,XXXXXXXX,X_______,
  ____XX__,____XXXX,XXXX____,________,
  ___XXX__,____XX__,_XXX____,XX______,
  __XXX__X,XXX_____,__XX___X,XXXX____,
  _XXXXXXX,XXX_____,__XX___X,XX______,
  __XXXXX_,________,__XX__XX,X_______,
  ________,________,__XXXXXX,________,
  ________,________,___XXXX_,________,
  ________,XXXX____,__XXXX__,________,
  _XXXXXXX,XXXX____,_XXXXXX_,___X____,
  _XXXXXXX,_______X,XXX__XXX,___XXX__,
  _XXX____,_____XXX,XX___XXX,X_XXX___,
  ________,___XXXXX,______XX,XXXXX___,
  ________,____XXX_,_______X,XXXX____,
  ________,____X___,________,_XX_____,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_7ED3[116] = { /* code 7ED3 */
  _____X__,________,___XXX__,________,
  _____XXX,________,___XXX__,________,
  _____XXX,________,___XXX__,________,
  ____XXX_,________,___XXX__,________,
  ____XXX_,________,___XXX__,________,
  ____XX__,____XXXX,XXXXXXXX,XXXXXX__,
  ___XXX__,_X__XXXX,XXXXXXXX,XXXXXX__,
  __XXX___,_XXX____,___XXX__,________,
  __XX____,XXX_____,___XXX__,________,
  _XXX____,XXX_____,___XXX__,________,
  XXXXXXXX,XX______,___XXX__,________,
  _XXXXXXX,X____XXX,XXXXXXXX,XXXX____,
  ______XX,X____XXX,XXXXXXXX,XXXX____,
  _____XXX,________,________,________,
  _____XX_,________,________,________,
  ____XXX_,________,________,________,
  ___XXX__,______XX,XXXXXXXX,XXXX____,
  __XXX__X,XXX___XX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXX___XX,X_______,_XXX____,
  _XXXXXXX,______XX,X_______,_XXX____,
  __X_____,______XX,X_______,_XXX____,
  ________,______XX,X_______,_XXX____,
  ________,______XX,X_______,_XXX____,
  _______X,XXXX__XX,X_______,_XXX____,
  XXXXXXXX,XXXX__XX,XXXXXXXX,XXXX____,
  _XXXXXXX,X_____XX,XXXXXXXX,XXXX____,
  _XXX____,______XX,X_______,_XXX____,
  ________,______XX,X_______,_XXX____,
  ________,______XX,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_7EDF[120] = { /* code 7EDF */
  ________,________,__XX____,________,
  _____XX_,________,__XXX___,________,
  _____XXX,________,__XXX___,________,
  ____XXX_,________,___XX___,________,
  ____XXX_,___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,___XXXXX,XXXXXXXX,XXXXX___,
  ___XX___,___XXXXX,XXXXXXXX,XXXXX___,
  __XXX___,XXX_____,_XX_____,________,
  __XX____,XXX_____,_XXX____,________,
  _XXX___X,XX______,XXX_____,________,
  XXXXXXXX,XX_____X,XX_____X,X_______,
  _XXXXXXX,X______X,X_____XX,XX______,
  ______XX,______XX,_______X,XX______,
  _____XXX,____XXXX,________,XXX_____,
  ____XXX_,____XXXX,XXXXXXXX,XXXX____,
  ____XX__,____XXXX,XXXXXXXX,_XXXX___,
  ___XXX__,___X_XX_,XX___XX_,__X_____,
  __XXXXXX,XXX_____,XX___XX_,________,
  _XXXXXXX,XXX_____,XX___XX_,________,
  __XXXX__,________,XX___XX_,________,
  ________,________,XX___XX_,________,
  ________,_______X,XX___XX_,________,
  ________,__XX___X,XX___XX_,________,
  ______XX,XXXX__XX,X____XX_,___X____,
  _XXXXXXX,XXX___XX,X____XX_,___XXX__,
  _XXXXXX_,_____XXX,_____XX_,___XX___,
  _XXX____,____XXX_,_____XXX,XXXXX___,
  ________,__XXXX__,_____XXX,XXXX____,
  ________,___XX___,______XX,XXX_____,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_7F6E[108] = { /* code 7F6E */
  ___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XX___,__XX____,XXX____X,XX______,
  ___XX___,__XX____,XXX____X,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,____X___,________,________,
  ________,_____XXX,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,_____XX_,________,________,
  ________,____XXX_,________,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XX_,________,_____XX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XX_,________,_____XX_,________,
  _____XX_,________,_____XX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XX_,________,_____XX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XX_,________,_____XX_,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_81EA[ 87] = { /* code 81EA */
  ________,XX______,________,
  ________,XXX_____,________,
  _______X,XX______,________,
  _______X,XX______,________,
  _______X,XX______,________,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXX_____,________,___XXX__,
  XXX_____,________,___XXX__,
  XXX_____,________,___XXX__,
  XXX_____,________,___XXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXX_____,________,___XXX__,
  XXX_____,________,___XXX__,
  XXX_____,________,___XXX__,
  XXX_____,________,___XXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXX_____,________,___XXX__,
  XXX_____,________,___XXX__,
  XXX_____,________,___XXX__,
  XXX_____,________,___XXX__,
  XXX_____,________,___XXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXX_____,________,___XXX__,
  XXX_____,________,___XXX__,
  XXX_____,________,___XXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_82F1[112] = { /* code 82F1 */
  ________,XX______,__XX____,________,
  ________,XX______,__XX____,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,XX______,__XX____,________,
  ________,XX___XX_,__XX____,________,
  ________,_____XXX,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,XXXXXXX_,________,
  _____XX_,_____XX_,_____XX_,________,
  _____XX_,_____XX_,_____XX_,________,
  _____XX_,_____XX_,_____XX_,________,
  _____XX_,_____XX_,_____XX_,________,
  _____XX_,_____XX_,_____XX_,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,____XX_X,X_______,________,
  ________,___XXX_X,XX______,________,
  ________,__XXX___,XXX_____,________,
  ________,_XXX____,_XXXX___,________,
  _______X,XXX_____,__XXXX__,________,
  _____XXX,XX______,___XXXXX,X_______,
  __XXXXXX,________,_____XXX,XXXX____,
  _XXXXX__,________,_______X,XXX_____,
  __XX____,________,________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_83DC[116] = { /* code 83DC */
  ________,_XXX____,__XXX___,________,
  ________,_XXX____,__XXX___,________,
  ________,_XXX____,__XXX___,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,_XXX____,__XXX___,________,
  ________,_XXX____,__XXX___,________,
  ________,________,______XX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ____XX__,______X_,_______X,________,
  ______X_,_____XXX,_______X,XX______,
  _____XXX,_____XXX,______XX,X_______,
  _____XXX,______XX,X____XXX,________,
  ______XX,X_____XX,_____XXX,________,
  _______X,X_____XX,_____XX_,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,__XXX_XX,_XXX____,________,
  ________,_XXX__XX,__XXX___,________,
  ________,XXX___XX,___XXXX_,________,
  _______X,XX____XX,____XXXX,________,
  _____XXX,X_____XX,_____XXX,XXX_____,
  ___XXXXX,______XX,_______X,XXXXXX__,
  _XXXXX__,______XX,________,XXXX____,
  __XXX___,______XX,________,__XX____,
  ________,______XX,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_8868[116] = { /* code 8868 */
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  __X_____,_____XX_,________,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,__XXX__X,________,________,
  ________,_XXX__XX,_______X,________,
  ________,XXX___XX,X_____XX,X_______,
  ______XX,XXX____X,X____XXX,X_______,
  _____XXX,XXX____X,XX__XXXX,________,
  ___XXXXX,XXX_____,XXXXXX__,________,
  __XXXX__,XXX_____,XXXXX___,________,
  XXXXX___,XXX____X,_XXXX___,________,
  _XX_____,XXX__XXX,__XXXX__,________,
  ________,XXX_XXXX,___XXXXX,X_______,
  ________,XXXXXXX_,_____XXX,XXXX____,
  ________,XXXXX___,______XX,XXXX____,
  ________,XXX_____,________,_XXX____,
  ________,_X______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_8A00[116] = { /* code 8A00 */
  ________,____XX__,________,________,
  ________,___XXX__,________,________,
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ________,________,________,________,
  ________,________,________,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXX_,________,_____XXX,________,
  ____XXX_,________,_____XXX,________,
  ____XXX_,________,_____XXX,________,
  ____XXX_,________,_____XXX,________,
  ____XXX_,________,_____XXX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXX_,________,_____XXX,________,
  ____XXX_,________,_____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_8BBE[116] = { /* code 8BBE */
  ____X___,________,________,________,
  ___XXX__,_____XXX,XXXXXXX_,________,
  ___XXXX_,_____XXX,XXXXXXX_,________,
  ____XXXX,_____XX_,_____XX_,________,
  _____XXX,_____XX_,_____XX_,________,
  ______XX,X____XX_,_____XX_,________,
  ________,_____XX_,_____XX_,________,
  ________,____XXX_,_____XX_,________,
  ________,____XXX_,_____XX_,________,
  ________,___XXX__,_____XXX,________,
  XXXXXXX_,__XXXX__,_____XXX,XXXXX___,
  XXXXXXX_,_XXXX___,_____XXX,XXXXX___,
  _____XX_,___X____,________,________,
  _____XX_,__XXXXXX,XXXXXXXX,XX______,
  _____XX_,__XXXXXX,XXXXXXXX,XX______,
  _____XX_,__XXXXXX,XXXXXXXX,X_______,
  _____XX_,_____XX_,______XX,X_______,
  _____XX_,_____XXX,______XX,X_______,
  _____XX_,______XX,_____XXX,________,
  _____XX_,______XX,X____XXX,________,
  _____XX_,_X_____X,X___XXX_,________,
  _____XX_,XXX____X,XX_XXX__,________,
  _____XXX,XXX_____,XXXXXX__,________,
  _____XXX,XX______,_XXXX___,________,
  _____XXX,X_______,XXXXXX__,________,
  ____XXXX,______XX,XX_XXXXX,________,
  ____XXX_,____XXXX,_____XXX,XXXXXX__,
  _____X__,XXXXXXX_,_______X,XXXXX___,
  ________,_XXX____,________,__XX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_8BD5[120] = { /* code 8BD5 */
  ________,________,___XX___,X_______,
  ___X____,________,___XX__X,XX______,
  __XXX___,________,___XX___,XXX_____,
  ___XXX__,________,___XX___,_XXX____,
  ____XXX_,________,___XX___,_XXX____,
  ____XXXX,________,___XX___,________,
  _____X__,________,___XX___,________,
  ________,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,________,___XX___,________,
  XXXXXX__,________,___XX___,________,
  XXXXXX__,________,___XX___,________,
  X___XX__,________,___XXX__,________,
  ____XX__,__XXXXXX,XX_XXX__,________,
  ____XX__,__XXXXXX,XX_XXX__,________,
  ____XX__,_____XX_,____XX__,________,
  ____XX__,_____XX_,____XX__,________,
  ____XX__,_____XX_,____XX__,________,
  ____XX__,_____XX_,____XXX_,________,
  ____XX__,_____XX_,____XXX_,________,
  ____XX__,_X___XX_,_____XX_,________,
  ____XX__,XXX__XX_,_____XXX,________,
  ____XX_X,XX___XX_,_XX__XXX,___X____,
  ____XXXX,X____XXX,XXX___XX,___XX___,
  ____XXXX,_XXXXXXX,XX____XX,X__XX___,
  ___XXXX_,__XXXX__,_______X,XXXXX___,
  ____XX__,__X_____,_______X,XXXXX___,
  ____X___,________,________,XXXX____,
  ________,________,________,_XXX____,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_8BED[116] = { /* code 8BED */
  ____X___,________,________,________,
  ___XX___,__XXXXXX,XXXXXXXX,XXXX____,
  ___XXX__,__XXXXXX,XXXXXXXX,XXXX____,
  ____XXX_,________,_XX_____,________,
  _____XXX,________,_XX_____,________,
  ______X_,________,_XX_____,________,
  ________,___XXXXX,XXXXXXXX,XXX_____,
  ________,___XXXXX,XXXXXXXX,XXX_____,
  ________,________,XX______,XX______,
  XXXXXXX_,________,XX______,XX______,
  XXXXXXX_,_______X,XX______,XX______,
  XXXXXXX_,_______X,XX_____X,XX______,
  _____XX_,_______X,XX_____X,XX______,
  _____XX_,_XXXXXXX,XXXXXXXX,XXXXXX__,
  _____XX_,_XXXXXXX,XXXXXXXX,XXXXXX__,
  _____XX_,________,________,________,
  _____XX_,________,________,________,
  _____XX_,________,________,________,
  _____XX_,_____XXX,XXXXXXXX,XXX_____,
  _____XX_,_X___XXX,XXXXXXXX,XXX_____,
  _____XX_,XX___XX_,________,XXX_____,
  _____XXX,XXX__XX_,________,XXX_____,
  _____XXX,XX___XX_,________,XXX_____,
  _____XXX,X____XX_,________,XXX_____,
  ____XXXX,_____XX_,________,XXX_____,
  ____XXX_,_____XXX,XXXXXXXX,XXX_____,
  ____XX__,_____XXX,XXXXXXXX,XXX_____,
  _____X__,_____XX_,________,XXX_____,
  ________,_____XX_,________,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_8BFB[116] = { /* code 8BFB */
  ________,________,_XXX____,________,
  __XX____,________,_XXX____,________,
  __XXX___,________,_XXX____,________,
  ___XXX__,________,_XXX____,________,
  ___XXX__,__XXXXXX,XXXXXXXX,XXX_____,
  ____XX__,__XXXXXX,XXXXXXXX,XXX_____,
  ________,________,_XXX____,________,
  ________,________,_XXX____,________,
  ________,_XXXXXXX,XXXXXXXX,XXXX____,
  ________,_XXXXXXX,XXXXXXXX,XXXX____,
  XXXXXX__,____X___,________,_XX_____,
  XXXXXX__,____XX__,___XX___,XXX_____,
  ____XX__,____XXXX,___XX___,XX______,
  ____XX__,_____XXX,X__XX___,_X______,
  ____XX__,__X____X,X__XX___,________,
  ____XX__,__XXX___,___XX___,________,
  ____XX__,__XXXX__,__XXX___,________,
  ____XX__,____XXX_,__XXX___,________,
  ____XX__,_____X__,__XX____,________,
  ____XX__,_XXXXXXX,XXXXXXXX,XXXX____,
  ____XX__,_XXXXXXX,XXXXXXXX,XXXX____,
  ____XX_X,X_______,_XXX____,________,
  ____XXXX,X_______,_XX_____,________,
  ____XXXX,________,XXX__XX_,________,
  ___XXXX_,_______X,XX__XXXX,________,
  ___XXX__,______XX,X____XXX,XX______,
  ___XX___,____XXXX,_______X,XXX_____,
  ________,_XXXXX__,________,XXXX____,
  ________,__XX____,________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_8D1F[120] = { /* code 8D1F */
  ________,__XX____,________,________,
  ________,__XXX___,________,________,
  ________,_XXX____,________,________,
  ________,_XXX____,________,________,
  ________,XXXXXXXX,XXXXXX__,________,
  _______X,XXXXXXXX,XXXXXX__,________,
  ______XX,X_______,__XXX___,________,
  _____XXX,________,__XXX___,________,
  ____XXX_,________,_XXX____,________,
  __XXXX__,________,_XX_____,________,
  _XXXX_XX,XXXXXXXX,XXXXXXXX,XX______,
  __XX__XX,XXXXXXXX,XXXXXXXX,XX______,
  ______XX,________,________,XX______,
  ______XX,________,________,XX______,
  ______XX,________,________,XX______,
  ______XX,______XX,X_______,XX______,
  ______XX,______XX,X_______,XX______,
  ______XX,______XX,X_______,XX______,
  ______XX,______XX,________,XX______,
  ______XX,______XX,________,XX______,
  ______XX,_____XXX,________,XX______,
  ______XX,_____XXX,________,XX______,
  ______XX,____XXX_,__X_____,________,
  ________,___XXXX_,__XXX___,________,
  ________,__XXXX__,_XXXXXX_,________,
  ________,XXXXX___,____XXXX,X_______,
  ____XXXX,XXX_____,______XX,XXX_____,
  _XXXXXXX,X_______,________,XXXX____,
  __XXXX__,________,________,_XXX____,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_8F7D[116] = { /* code 8F7D */
  _______X,XX______,_XXX____,________,
  _______X,XX______,_XXX___X,X_______,
  _______X,XX______,_XXX___X,XX______,
  __XXXXXX,XXXXXXX_,_XXX____,XXX_____,
  __XXXXXX,XXXXXXX_,_XXX____,XXX_____,
  _______X,XX______,_XXX____,________,
  _______X,XX______,_XXX____,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  _______X,________,__XX____,________,
  _______X,XX______,__XX____,________,
  ______XX,X_______,__XX____,X_______,
  _XXXXXXX,XXXXXXXX,__XX____,XXX_____,
  _XXXXXXX,XXXXXXXX,__XX____,XX______,
  ____XXX_,________,__XX___X,XX______,
  ____XX__,XXX_____,__XXX__X,XX______,
  ___XX___,XXX_____,___XX__X,X_______,
  __XXX___,XXX_____,___XX_XX,X_______,
  __XXXXXX,XXXXXXX_,___XX_XX,________,
  __XXXXXX,XXXXXXX_,___XXXXX,________,
  ________,XXX_____,____XXX_,________,
  ________,XXX_____,____XXX_,________,
  ________,XXXXXXXX,___XXXX_,________,
  _XXXXXXX,XXXXXXX_,___XXXXX,___X____,
  _XXXXXXX,XXX_____,__XXX_XX,___XX___,
  _XXX____,XXX_____,XXXX__XX,X_XXX___,
  ________,XXX____X,XXX____X,XXXXX___,
  ________,XXX___XX,XX______,XXXX____,
  ________,XXX____X,________,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_8FC7[116] = { /* code 8FC7 */
  ________,________,_____XXX,________,
  ____X___,________,_____XXX,________,
  ___XXX__,________,_____XXX,________,
  ___XXXX_,________,_____XXX,________,
  ____XXX_,________,_____XXX,________,
  _____XXX,________,_____XXX,________,
  _____XXX,X_XXXXXX,XXXXXXXX,XXXXX___,
  ______X_,__XXXXXX,XXXXXXXX,XXXXX___,
  ________,________,_____XXX,________,
  ________,________,_____XXX,________,
  ________,________,_____XXX,________,
  _XXXXXXX,____XXX_,_____XXX,________,
  _XXXXXXX,____XXX_,_____XXX,________,
  _XXXXXXX,_____XXX,_____XXX,________,
  _____XXX,_____XXX,_____XXX,________,
  _____XXX,______XX,X____XXX,________,
  _____XXX,______XX,X____XXX,________,
  _____XXX,______XX,_____XXX,________,
  _____XXX,________,_____XXX,________,
  _____XXX,________,_____XXX,________,
  _____XXX,________,_____XXX,________,
  _____XXX,________,_____XXX,________,
  _____XXX,________,_XXXXXXX,________,
  ____XXXX,X_______,__XXXXX_,________,
  ___XXXXX,XX______,__XX____,________,
  __XXXX__,XXXXX___,________,________,
  _XXXX___,_XXXXXXX,XXXXXXXX,XXXXX___,
  _XXX____,___XXXXX,XXXXXXXX,XXXXX___,
  __X_____,_______X,XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ32_963B[112] = { /* code 963B */
  XXXXXXXX,X_______,________,________,
  XXXXXXXX,X__XXXXX,XXXXXXXX,________,
  XXXXXXXX,X__XXXXX,XXXXXXXX,________,
  XX____XX,___XX___,______XX,________,
  XX___XXX,___XX___,______XX,________,
  XX___XXX,___XX___,______XX,________,
  XX___XX_,___XX___,______XX,________,
  XX___XX_,___XX___,______XX,________,
  XX__XXX_,___XX___,______XX,________,
  XX__XX__,___XXXXX,XXXXXXXX,________,
  XX__XXX_,___XXXXX,XXXXXXXX,________,
  XX___XXX,___XX___,______XX,________,
  XX____XX,___XX___,______XX,________,
  XX____XX,X__XX___,______XX,________,
  XX_____X,X__XX___,______XX,________,
  XX_____X,X__XX___,______XX,________,
  XX_____X,X__XXXXX,XXXXXXXX,________,
  XX____XX,X__XXXXX,XXXXXXXX,________,
  XX__XXXX,X__XX___,______XX,________,
  XX__XXXX,___XX___,______XX,________,
  XX__XX__,___XX___,______XX,________,
  XX______,___XX___,______XX,________,
  XX______,___XX___,______XX,________,
  XX______,___XX___,______XX,________,
  XX______,XXXXXXXX,XXXXXXXX,XXXX____,
  XX______,XXXXXXXX,XXXXXXXX,XXXX____,
  XX______,XXXXXXXX,XXXXXXXX,XXXX____,
  XX______,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontHZ32_CharInfo[56] = {
   {  24,  25,   0,   0,  24, acGUI_FontHZ32_03A9 } /* code 03A9, GREEK CAPITAL LETTER OMEGA */
  ,{  24,  29,   4,   2,  32, acGUI_FontHZ32_4E2D } /* code 4E2D */
  ,{  28,  28,   2,   2,  32, acGUI_FontHZ32_4E3B } /* code 4E3B */
  ,{  30,  29,   1,   2,  32, acGUI_FontHZ32_4FDD } /* code 4FDD */
  ,{  30,  29,   1,   2,  32, acGUI_FontHZ32_503C } /* code 503C */
  ,{  30,  30,   1,   1,  32, acGUI_FontHZ32_505C } /* code 505C */
  ,{  28,  29,   2,   2,  32, acGUI_FontHZ32_5145 } /* code 5145 */
  ,{  28,  29,   2,   2,  32, acGUI_FontHZ32_5173 } /* code 5173 */
  ,{  26,  29,   3,   2,  32, acGUI_FontHZ32_5185 } /* code 5185 */
  ,{  28,  28,   2,   3,  32, acGUI_FontHZ32_5217 } /* code 5217 */
  ,{  29,  29,   1,   2,  32, acGUI_FontHZ32_52A8 } /* code 52A8 */
  ,{  28,  29,   2,   2,  32, acGUI_FontHZ32_5355 } /* code 5355 */
  ,{  28,  28,   1,   3,  32, acGUI_FontHZ32_538B } /* code 538B */
  ,{  29,  29,   2,   3,  32, acGUI_FontHZ32_53D6 } /* code 53D6 */
  ,{  28,  28,   2,   3,  32, acGUI_FontHZ32_53F7 } /* code 53F7 */
  ,{  30,  27,   1,   4,  32, acGUI_FontHZ32_5426 } /* code 5426 */
  ,{  30,  29,   1,   2,  32, acGUI_FontHZ32_59CB } /* code 59CB */
  ,{  28,  27,   2,   4,  32, acGUI_FontHZ32_5B50 } /* code 5B50 */
  ,{  29,  29,   1,   2,  32, acGUI_FontHZ32_5B58 } /* code 5B58 */
  ,{  29,  30,   1,   1,  32, acGUI_FontHZ32_5B9A } /* code 5B9A */
  ,{  28,  28,   2,   3,  32, acGUI_FontHZ32_5F00 } /* code 5F00 */
  ,{  29,  29,   2,   2,  32, acGUI_FontHZ32_5F0F } /* code 5F0F */
  ,{  30,  28,   1,   2,  32, acGUI_FontHZ32_6001 } /* code 6001 */
  ,{  29,  29,   1,   2,  32, acGUI_FontHZ32_62A4 } /* code 62A4 */
  ,{  30,  29,   1,   2,  32, acGUI_FontHZ32_63A7 } /* code 63A7 */
  ,{  30,  29,   1,   2,  32, acGUI_FontHZ32_653E } /* code 653E */
  ,{  28,  29,   2,   2,  32, acGUI_FontHZ32_6587 } /* code 6587 */
  ,{  29,  28,   2,   3,  32, acGUI_FontHZ32_662F } /* code 662F */
  ,{  28,  28,   2,   3,  32, acGUI_FontHZ32_679C } /* code 679C */
  ,{  30,  29,   1,   2,  32, acGUI_FontHZ32_6A21 } /* code 6A21 */
  ,{  28,  26,   2,   3,  32, acGUI_FontHZ32_6B62 } /* code 6B62 */
  ,{  29,  30,   2,   2,  32, acGUI_FontHZ32_6D41 } /* code 6D41 */
  ,{  29,  28,   1,   3,  32, acGUI_FontHZ32_6D4B } /* code 6D4B */
  ,{  30,  30,   1,   2,  32, acGUI_FontHZ32_6E90 } /* code 6E90 */
  ,{  28,  29,   3,   2,  32, acGUI_FontHZ32_7535 } /* code 7535 */
  ,{  29,  30,   1,   1,  32, acGUI_FontHZ32_786E } /* code 786E */
  ,{  30,  29,   1,   2,  32, acGUI_FontHZ32_7A0B } /* code 7A0B */
  ,{  28,  30,   2,   2,  32, acGUI_FontHZ32_7C7B } /* code 7C7B */
  ,{  28,  29,   2,   2,  32, acGUI_FontHZ32_7CFB } /* code 7CFB */
  ,{  30,  30,   1,   2,  32, acGUI_FontHZ32_7EBF } /* code 7EBF */
  ,{  30,  29,   1,   2,  32, acGUI_FontHZ32_7ED3 } /* code 7ED3 */
  ,{  30,  30,   1,   2,  32, acGUI_FontHZ32_7EDF } /* code 7EDF */
  ,{  28,  27,   2,   3,  32, acGUI_FontHZ32_7F6E } /* code 7F6E */
  ,{  22,  29,   5,   2,  32, acGUI_FontHZ32_81EA } /* code 81EA */
  ,{  28,  28,   2,   3,  32, acGUI_FontHZ32_82F1 } /* code 82F1 */
  ,{  30,  29,   1,   2,  32, acGUI_FontHZ32_83DC } /* code 83DC */
  ,{  29,  29,   2,   2,  32, acGUI_FontHZ32_8868 } /* code 8868 */
  ,{  27,  29,   2,   2,  32, acGUI_FontHZ32_8A00 } /* code 8A00 */
  ,{  30,  29,   1,   2,  32, acGUI_FontHZ32_8BBE } /* code 8BBE */
  ,{  30,  30,   1,   2,  32, acGUI_FontHZ32_8BD5 } /* code 8BD5 */
  ,{  30,  29,   1,   2,  32, acGUI_FontHZ32_8BED } /* code 8BED */
  ,{  28,  29,   2,   2,  32, acGUI_FontHZ32_8BFB } /* code 8BFB */
  ,{  29,  30,   1,   2,  32, acGUI_FontHZ32_8D1F } /* code 8D1F */
  ,{  30,  29,   1,   2,  32, acGUI_FontHZ32_8F7D } /* code 8F7D */
  ,{  30,  29,   1,   2,  32, acGUI_FontHZ32_8FC7 } /* code 8FC7 */
  ,{  28,  28,   3,   3,  32, acGUI_FontHZ32_963B } /* code 963B */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop56 = {
   0x963B /* first character */
  ,0x963B /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 55] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop55 = {
   0x8FC7 /* first character */
  ,0x8FC7 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 54] /* address of first character */
  ,&GUI_FontHZ32_Prop56 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop54 = {
   0x8F7D /* first character */
  ,0x8F7D /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 53] /* address of first character */
  ,&GUI_FontHZ32_Prop55 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop53 = {
   0x8D1F /* first character */
  ,0x8D1F /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 52] /* address of first character */
  ,&GUI_FontHZ32_Prop54 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop52 = {
   0x8BFB /* first character */
  ,0x8BFB /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 51] /* address of first character */
  ,&GUI_FontHZ32_Prop53 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop51 = {
   0x8BED /* first character */
  ,0x8BED /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 50] /* address of first character */
  ,&GUI_FontHZ32_Prop52 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop50 = {
   0x8BD5 /* first character */
  ,0x8BD5 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 49] /* address of first character */
  ,&GUI_FontHZ32_Prop51 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop49 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 48] /* address of first character */
  ,&GUI_FontHZ32_Prop50 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop48 = {
   0x8A00 /* first character */
  ,0x8A00 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 47] /* address of first character */
  ,&GUI_FontHZ32_Prop49 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop47 = {
   0x8868 /* first character */
  ,0x8868 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 46] /* address of first character */
  ,&GUI_FontHZ32_Prop48 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop46 = {
   0x83DC /* first character */
  ,0x83DC /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 45] /* address of first character */
  ,&GUI_FontHZ32_Prop47 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop45 = {
   0x82F1 /* first character */
  ,0x82F1 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 44] /* address of first character */
  ,&GUI_FontHZ32_Prop46 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop44 = {
   0x81EA /* first character */
  ,0x81EA /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 43] /* address of first character */
  ,&GUI_FontHZ32_Prop45 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop43 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 42] /* address of first character */
  ,&GUI_FontHZ32_Prop44 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop42 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 41] /* address of first character */
  ,&GUI_FontHZ32_Prop43 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop41 = {
   0x7ED3 /* first character */
  ,0x7ED3 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 40] /* address of first character */
  ,&GUI_FontHZ32_Prop42 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop40 = {
   0x7EBF /* first character */
  ,0x7EBF /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 39] /* address of first character */
  ,&GUI_FontHZ32_Prop41 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop39 = {
   0x7CFB /* first character */
  ,0x7CFB /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 38] /* address of first character */
  ,&GUI_FontHZ32_Prop40 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop38 = {
   0x7C7B /* first character */
  ,0x7C7B /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 37] /* address of first character */
  ,&GUI_FontHZ32_Prop39 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop37 = {
   0x7A0B /* first character */
  ,0x7A0B /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 36] /* address of first character */
  ,&GUI_FontHZ32_Prop38 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop36 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 35] /* address of first character */
  ,&GUI_FontHZ32_Prop37 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop35 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 34] /* address of first character */
  ,&GUI_FontHZ32_Prop36 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop34 = {
   0x6E90 /* first character */
  ,0x6E90 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 33] /* address of first character */
  ,&GUI_FontHZ32_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop33 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 32] /* address of first character */
  ,&GUI_FontHZ32_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop32 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 31] /* address of first character */
  ,&GUI_FontHZ32_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop31 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 30] /* address of first character */
  ,&GUI_FontHZ32_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop30 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 29] /* address of first character */
  ,&GUI_FontHZ32_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop29 = {
   0x679C /* first character */
  ,0x679C /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 28] /* address of first character */
  ,&GUI_FontHZ32_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop28 = {
   0x662F /* first character */
  ,0x662F /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 27] /* address of first character */
  ,&GUI_FontHZ32_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop27 = {
   0x6587 /* first character */
  ,0x6587 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 26] /* address of first character */
  ,&GUI_FontHZ32_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop26 = {
   0x653E /* first character */
  ,0x653E /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 25] /* address of first character */
  ,&GUI_FontHZ32_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop25 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 24] /* address of first character */
  ,&GUI_FontHZ32_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop24 = {
   0x62A4 /* first character */
  ,0x62A4 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 23] /* address of first character */
  ,&GUI_FontHZ32_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop23 = {
   0x6001 /* first character */
  ,0x6001 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 22] /* address of first character */
  ,&GUI_FontHZ32_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop22 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 21] /* address of first character */
  ,&GUI_FontHZ32_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop21 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 20] /* address of first character */
  ,&GUI_FontHZ32_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop20 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 19] /* address of first character */
  ,&GUI_FontHZ32_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop19 = {
   0x5B58 /* first character */
  ,0x5B58 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 18] /* address of first character */
  ,&GUI_FontHZ32_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop18 = {
   0x5B50 /* first character */
  ,0x5B50 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 17] /* address of first character */
  ,&GUI_FontHZ32_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop17 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 16] /* address of first character */
  ,&GUI_FontHZ32_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop16 = {
   0x5426 /* first character */
  ,0x5426 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 15] /* address of first character */
  ,&GUI_FontHZ32_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop15 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 14] /* address of first character */
  ,&GUI_FontHZ32_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop14 = {
   0x53D6 /* first character */
  ,0x53D6 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 13] /* address of first character */
  ,&GUI_FontHZ32_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop13 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 12] /* address of first character */
  ,&GUI_FontHZ32_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop12 = {
   0x5355 /* first character */
  ,0x5355 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 11] /* address of first character */
  ,&GUI_FontHZ32_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop11 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontHZ32_CharInfo[ 10] /* address of first character */
  ,&GUI_FontHZ32_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop10 = {
   0x5217 /* first character */
  ,0x5217 /* last character  */
  ,&GUI_FontHZ32_CharInfo[  9] /* address of first character */
  ,&GUI_FontHZ32_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop9 = {
   0x5185 /* first character */
  ,0x5185 /* last character  */
  ,&GUI_FontHZ32_CharInfo[  8] /* address of first character */
  ,&GUI_FontHZ32_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop8 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontHZ32_CharInfo[  7] /* address of first character */
  ,&GUI_FontHZ32_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop7 = {
   0x5145 /* first character */
  ,0x5145 /* last character  */
  ,&GUI_FontHZ32_CharInfo[  6] /* address of first character */
  ,&GUI_FontHZ32_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop6 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontHZ32_CharInfo[  5] /* address of first character */
  ,&GUI_FontHZ32_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop5 = {
   0x503C /* first character */
  ,0x503C /* last character  */
  ,&GUI_FontHZ32_CharInfo[  4] /* address of first character */
  ,&GUI_FontHZ32_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop4 = {
   0x4FDD /* first character */
  ,0x4FDD /* last character  */
  ,&GUI_FontHZ32_CharInfo[  3] /* address of first character */
  ,&GUI_FontHZ32_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop3 = {
   0x4E3B /* first character */
  ,0x4E3B /* last character  */
  ,&GUI_FontHZ32_CharInfo[  2] /* address of first character */
  ,&GUI_FontHZ32_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop2 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_FontHZ32_CharInfo[  1] /* address of first character */
  ,&GUI_FontHZ32_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ32_Prop1 = {
   0x03A9 /* first character */
  ,0x03A9 /* last character  */
  ,&GUI_FontHZ32_CharInfo[  0] /* address of first character */
  ,&GUI_FontHZ32_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHZ32 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHZ32_Prop1}
  ,28 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,21 /* Height of capital characters */
};

