/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: symbol.c                                              *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      22                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  22                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x4A (74)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsymbol;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsymbol_004A[ 44] = { /* code 004A, LATIN CAPITAL LETTER J */
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x0F,0x00,0x0F,0x00,0x1E,
    0x00,0x1E,0x00,0x1E,0x00,0x1E,0x00,0x3C,0x00,0x3C,0x00,0x3C,0x00,0x3C,0x00,0x78,
    0x00,0x78,0x00,0x78,0xFF,0xF0,0xFF,0xE0,0x00,0x00,0x00,0x00};
    
GUI_CONST_STORAGE unsigned char acGUI_Fontsymbol_0069[ 44] = { /* code 0069, LATIN SMALL LETTER I */
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x07,0x00,0x0F,0x00,0x0E,0x00,
    0x00,0x00,0x0E,0x00,0x1E,0x00,0x1C,0x00,0x1C,0x00,0x3C,0x00,0x3C,0x00,0x38,0x00,
    0x38,0x00,0x78,0x00,0x70,0x00,0x70,0x00,0x00,0x00,0x00,0x00};

GUI_CONST_STORAGE unsigned char acGUI_Fontsymbol_006E[ 44] = { /* code 006E, LATIN SMALL LETTER N */
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    0x00,0x00,0x3F,0xC0,0x1F,0x80,0x03,0x80,0x03,0x80,0x03,0x80,0x07,0x00,0x07,0x00,
    0x07,0x00,0x07,0x00,0x0F,0x00,0x0E,0x00,0x00,0x00,0x00,0x00};
    
GUI_CONST_STORAGE unsigned char acGUI_Fontsymbol_006B[ 44] = { /* code 006B, LATIN SMALL LETTER K */
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x07,0x00,0x07,0x00,0x0F,0x00,
    0x0F,0x00,0x0F,0x1E,0x0E,0x38,0x1E,0xF0,0x1F,0xE0,0x1F,0xE0,0x1E,0xE0,0x3C,0xF0,
    0x38,0xF0,0x38,0xF0,0x38,0xF0,0x30,0x30,0x00,0x00,0x00,0x00};

GUI_CONST_STORAGE unsigned char acGUI_Fontsymbol_006F[ 44] = { /* code 006F, LATIN SMALL LETTER O */
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    0x00,0x00,0x07,0xFE,0x0F,0xFF,0x0E,0x0F,0x1E,0x0E,0x1E,0x1E,0x1C,0x1E,0x3C,0x1C,
    0x3C,0x3C,0x38,0x3C,0x1F,0xF8,0x0F,0xF0,0x00,0x00,0x00,0x00};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Fontsymbol_CharInfo[5] = {
    {   16,  22,   0,   0,   13, acGUI_Fontsymbol_004A } /* code 004A, LATIN CAPITAL LETTER J */
   ,{   16,  22,   0,   0,    6, acGUI_Fontsymbol_0069 } /* code 0069, LATIN SMALL LETTER I */
   ,{   16,  22,   0,   0,    7, acGUI_Fontsymbol_006E } /* code 006E, LATIN SMALL LETTER N */
   ,{   16,  22,   0,   0,   11, acGUI_Fontsymbol_006B } /* code 006B, LATIN SMALL LETTER K */
   ,{   16,  22,   0,   0,   16, acGUI_Fontsymbol_006F } /* code 006F, LATIN SMALL LETTER O */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsymbol_Prop5 = {
   0x006F /* first character */
  ,0x006F /* last character  */
  ,&GUI_Fontsymbol_CharInfo[  4] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsymbol_Prop4 = {
   0x006B /* first character */
  ,0x006B /* last character  */
  ,&GUI_Fontsymbol_CharInfo[  3] /* address of first character */
  ,&GUI_Fontsymbol_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsymbol_Prop3 = {
   0x006E /* first character */
  ,0x006E /* last character  */
  ,&GUI_Fontsymbol_CharInfo[  2] /* address of first character */
  ,&GUI_Fontsymbol_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsymbol_Prop2 = {
   0x0069 /* first character */
  ,0x0069 /* last character  */
  ,&GUI_Fontsymbol_CharInfo[  1] /* address of first character */
  ,&GUI_Fontsymbol_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsymbol_Prop1 = {
   0x004A /* first character */
  ,0x004A /* last character  */
  ,&GUI_Fontsymbol_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsymbol_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsymbol = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,22 /* height of font  */
  ,22 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsymbol_Prop1}
  ,15 /* Baseline */
  ,22 /* Height of lowercase characters */
  ,22 /* Height of capital characters */
};

